version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: employee_attendance
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin234
      PGDATABASE: employee_attendance
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - "3003:3003"

  employee_portal:
    build: ./Employee_Portal
    ports:
      - "8006:80"
    depends_on:
      - backend

  hr_portal:
    build: ./HR_Portal
    ports:
      - "8007:80"
    depends_on:
      - backend

volumes:
  postgres_data:

